# A uxsm session on NixOS, started by a real LightDM instance.
#
# This follows test/integration/08-display-manager.sh, but declares the entire
# machine—display manager, autologin, desktop, and session entry—and starts it
# through the nixpkgs test framework. It verifies both that the Nix package
# installs everything required, beginning with systemd units, and that uxsm
# works on a distribution whose paths differ from all the others.
{ pkgs, uxsm }:

let
  # The session entry visible to LightDM. On NixOS it is not generated by
  # `uxsm entry`: /usr/local/share/xsessions does not exist, and sessions are
  # declared through services.displayManager.sessionPackages.
  session = pkgs.writeTextFile {
    name = "bspwm-uxsm-session";
    # services.displayManager.sessionPackages requires the package to declare
    # its sessions; the display manager uses this to name them.
    derivationArgs.passthru.providedSessions = [ "bspwm-uxsm" ];
    destination = "/share/xsessions/bspwm-uxsm.desktop";
    text = ''
      [Desktop Entry]
      Type=Application
      Name=bspwm (uxsm)
      Comment=bspwm as a systemd --user session
      Exec=${uxsm}/bin/uxsm start -D bspwm -- ${pkgs.bspwm}/bin/bspwm
      DesktopNames=bspwm
    '';
  };
in
pkgs.testers.runNixOSTest {
  name = "uxsm-session";

  nodes.machine =
    { ... }:
    {
      users.users.alice = {
        isNormalUser = true;
        uid = 1000;
      };

      services.xserver.enable = true;
      services.xserver.displayManager.lightdm = {
        enable = true;
        # No greeter: autologin with zero delay makes LightDM enter directly.
        greeter.enable = false;
      };
      services.displayManager = {
        autoLogin = {
          enable = true;
          user = "alice";
        };
        defaultSession = "bspwm-uxsm";
        sessionPackages = [ session ];
      };

      # systemd.packages places uxsm unit templates where each user's manager
      # can find them.
      systemd.packages = [ uxsm ];
      environment.systemPackages = [
        uxsm
        pkgs.bspwm
      ];

      virtualisation.memorySize = 2048;
    };

  testScript = ''
    machine.wait_for_unit("display-manager.service")
    # Alice has no systemd user manager until LightDM logs in, so nothing can be
    # queried before then.
    machine.wait_for_unit("user@1000.service")

    def user_unit(unit):
        return f"systemctl --user -M alice@ is-active {unit}"

    def dump(what):
        # Diagnostics needed when the session fails to start: system output,
        # the session's final output, and installed user units.
        print(f"=== {what} ===")
        print(machine.execute("journalctl -b -n 120 --no-pager")[1])
        print(machine.execute("cat /home/alice/.xsession-errors 2>/dev/null")[1])
        print(machine.execute("ls /etc/systemd/user/ 2>/dev/null")[1])
        print(machine.execute("tail -n 40 /var/log/lightdm/lightdm.log 2>/dev/null")[1])

    # The complete session as assembled by uxsm: the desktop as a service and,
    # after waiting for the window manager, the graphical session.
    try:
        machine.wait_until_succeeds(user_unit("uxsm-desktop@bspwm.service"), timeout=90)
    except Exception:
        dump("the uxsm session did not start")
        raise
    machine.wait_until_succeeds(user_unit("graphical-session.target"), timeout=60)

    # The service's main process is the desktop, with no intermediary.
    pid = machine.succeed(
        "systemctl --user -M alice@ show -p MainPID --value uxsm-desktop@bspwm.service"
    ).strip()
    comm = machine.succeed(f"cat /proc/{pid}/comm").strip()
    assert comm == "bspwm", f"the main process of the desktop service is {comm}, not bspwm"

    # The identity computed by uxsm reaches the desktop.
    environ = machine.succeed(f"tr '\\0' '\\n' < /proc/{pid}/environ")
    assert "XDG_CURRENT_DESKTOP=bspwm" in environ, environ
    assert "XDG_SESSION_TYPE=x11" in environ, environ

    # Closing from the display manager also stops the session.
    machine.succeed("systemctl stop display-manager.service")
    machine.wait_until_fails(user_unit("uxsm-desktop@bspwm.service"))
    machine.wait_until_fails(user_unit("graphical-session.target"))
  '';
}
