package sessionentry

import "strings"

// startsOwnAutostart says whether any desktop name belongs to a known session
// that launches XDG autostart entries itself, and identifies that name.
//
// It has one purpose: making entries generated by uxsm include `--no-autostart`
// for those sessions. If both launched autostart, every entry would start twice;
// this was verified with Xfce, where neither xfce4-session nor systemd checks
// whether the other already launched it.
//
// uxsm makes no assumptions about a session absent from the table: the entry is
// generated without the option and uxsm launches autostart, as expected for a
// systemd-managed session and as uwsm does. Users whose session launches its own
// autostart and produces duplicates can add the option.
func startsOwnAutostart(names []string) (string, bool) {
	for _, name := range names {
		if ownAutostart[strings.ToLower(name)] {
			return name, true
		}
	}
	return "", false
}

// ownAutostart maps each lowercase known desktop name to whether that session
// launches XDG autostart itself.
var ownAutostart = func() map[string]bool {
	m := make(map[string]bool)
	for _, k := range known {
		for _, name := range k.DesktopNames {
			// One name can occur in multiple entries—"GNOME" in GNOME, Budgie,
			// and openbox-gnome—and one launcher is enough.
			m[strings.ToLower(name)] = m[strings.ToLower(name)] || k.OwnAutostart
		}
	}
	return m
}()
