package sessionentry

// Known contains data for a known desktop. It serves two purposes: filling in
// data missing from an entry, whose own values always take precedence, and
// generating entries without an original entry through FromTable.
type Known struct {
	Name, Comment string
	DesktopNames  []string
	// Exec is the command that starts the desktop, taken from the entry's Exec=
	// but without a path so it works on every distribution. It is empty when no
	// command works everywhere, in which case FromTable cannot use it.
	Exec string
	// OwnAutostart says that this session launches XDG autostart entries itself,
	// so uxsm must not launch them too: the entry generated by uxsm entry
	// includes --no-autostart.
	//
	// This describes what the session does, not what it is. It usually correlates
	// with having a session manager—Xfce launches it, bspwm does not—but not
	// always: Enlightenment is a window manager that launches it, while
	// icewm-session is a scripted session that does not. Without the marker, uxsm
	// does not assume the session launches it: the option is omitted and uxsm
	// launches autostart.
	OwnAutostart bool
}

// known maps entry IDs to known desktops.
//
// This table comes from entries packaged by Arch, Debian 13, Ubuntu 24.04, and
// A test/xsessions.sh scan on Fedora 43 in September 2026 found one hundred
// distinct entries.
// Many never include DesktopNames=, while others include it only on some
// distributions: bspwm does on Arch and Debian, but not Ubuntu or Fedora. Each
// name comes from these sources in preference order:
//
//  1. DesktopNames= from any of those distributions.
//  2. XDG_CURRENT_DESKTOP set by the session launcher itself, preventing uxsm
//     from putting a different name in the manager than desktop processes see:
//     cinnamon-session takes it from DesktopName= in its .session, startlxde
//     exports LXDE, and dde-session exports DDE.
//  3. If none is set, as with window managers, the lowercase program name,
//     following those that do declare one (i3, bspwm, dwm, qtile, cwm,
//     spectrwm).
//
// Name= and Comment= come from the same entries.
var known = map[string]Known{
	// Desktop environments.
	"budgie-desktop.desktop": {
		Name: "Budgie Desktop", Comment: "This session logs you into the Budgie Desktop",
		DesktopNames: []string{"Budgie", "GNOME"}, // Debian, Ubuntu; Fedora only Budgie
		Exec:         "budgie-desktop",
		OwnAutostart: true,
	},
	"cinnamon.desktop": {
		Name: "Cinnamon", Comment: "This session logs you into Cinnamon",
		DesktopNames: []string{"X-Cinnamon"}, // cinnamon.session
		Exec:         "cinnamon-session-cinnamon",
		OwnAutostart: true,
	},
	"cinnamon2d.desktop": {
		Name: "Cinnamon (Software Rendering)", Comment: "This session logs you into Cinnamon (using software rendering)",
		DesktopNames: []string{"X-Cinnamon"}, // cinnamon2d.session
		Exec:         "cinnamon-session-cinnamon2d",
		OwnAutostart: true,
	},
	"deepin.desktop": {
		Name: "deepin", Comment: "Deepin Desktop Environment",
		DesktopNames: []string{"DDE"}, // dde-session
		Exec:         "dde-session",
		OwnAutostart: true,
	},
	// Enlightenment (0.27) does not launch XDG autostart entries: tests on Arch
	// and Ubuntu, with the desktop already visible and up to thirty seconds of
	// leeway, launched none. Its code does know about them—the "startup
	// applications" module reads them for selection—so it may launch entries
	// added through that module, but not the whole directory.
	"enlightenment.desktop": {
		Name: "Enlightenment", Comment: "Log in using Enlightenment",
		DesktopNames: []string{"Enlightenment"}, // all
		Exec:         "enlightenment_start",
	},
	// No Exec: the command is "env GNOME_SHELL_SESSION_MODE=classic gnome-session",
	// and a command-based instance would be named "env".
	"gnome-classic-xorg.desktop": {
		Name: "GNOME Classic on Xorg", Comment: "This session logs you into GNOME Classic",
		DesktopNames: []string{"GNOME-Classic", "GNOME"}, // all
		OwnAutostart: true,
	},
	// No Exec: the program is not in PATH and its path varies by distribution
	// (/usr/lib on Arch, /usr/libexec on Debian).
	"gnome-flashback-metacity.desktop": {
		Name: "GNOME Flashback (Metacity)", Comment: "This session logs you into GNOME Flashback with Metacity",
		DesktopNames: []string{"GNOME-Flashback", "GNOME"}, // all
		OwnAutostart: true,
	},
	"gnome-xorg.desktop": {
		Name: "GNOME on Xorg", Comment: "This session logs you into GNOME",
		DesktopNames: []string{"GNOME"}, // all
		Exec:         "gnome-session",
		OwnAutostart: true,
	},
	"LXDE.desktop": {
		Name: "LXDE", Comment: "LXDE - Lightweight X11 desktop environment",
		DesktopNames: []string{"LXDE"}, // startlxde
		Exec:         "startlxde",
		OwnAutostart: true,
	},
	"lxqt.desktop": {
		Name: "LXQt Desktop", Comment: "Lightweight Qt Desktop",
		DesktopNames: []string{"LXQt"}, // all
		Exec:         "startlxqt",
		OwnAutostart: true,
	},
	"mate.desktop": {
		Name: "MATE", Comment: "This session logs you into MATE",
		DesktopNames: []string{"MATE"}, // all
		Exec:         "mate-session",
		OwnAutostart: true,
	},
	// Plasma's X11 session is named plasmax11.desktop since Plasma 6 and was
	// previously plasma.desktop, as on Ubuntu 24.04.
	"plasma.desktop": {
		Name: "Plasma (X11)", Comment: "Plasma by KDE",
		DesktopNames: []string{"KDE"}, // Ubuntu
		Exec:         "startplasma-x11",
		OwnAutostart: true,
	},
	"plasmax11.desktop": {
		Name: "Plasma (X11)", Comment: "Plasma by KDE",
		DesktopNames: []string{"KDE"}, // Arch, Debian, Fedora
		Exec:         "startplasma-x11",
		OwnAutostart: true,
	},
	"xfce.desktop": {
		Name: "Xfce Session", Comment: "Use this session to run Xfce as your desktop environment",
		DesktopNames: []string{"XFCE"}, // all
		Exec:         "startxfce4",
		OwnAutostart: true,
	},

	// A window manager inside a desktop. Its Exec= is a script that starts the
	// window manager and then the desktop's session manager, so the name belongs
	// to the running desktop rather than the window manager or script:
	// sawfish-mate-session ends in mate-session, while openbox-gnome-session ends
	// in a gnome-session session with DesktopName=GNOME.
	//
	// Deliberately omitted: openbox-kde, e16-kde-session, and sawfish-kde4, which
	// end in startkde, a program Plasma no longer ships; e16-gnome2-session and
	// e16-gnome3-session from Fedora, where GNOME no longer has an X11 session;
	// and sawfish-lumina, because the name set by Lumina is unclear.
	"openbox-gnome.desktop": {
		Name: "GNOME/Openbox", Comment: "Use the Openbox window manager inside of the GNOME desktop environment",
		DesktopNames: []string{"GNOME"}, // openbox-gnome.session
		Exec:         "openbox-gnome-session",
		OwnAutostart: true,
	},
	"sawfish-kde5.desktop": {
		Name: "Sawfish/KDE5", Comment: "Use the Sawfish window manager inside of the KDE5 desktop environment",
		DesktopNames: []string{"KDE"}, // startplasma-x11
		Exec:         "sawfish-kde5-session",
		OwnAutostart: true,
	},
	"sawfish-mate.desktop": {
		Name: "Sawfish/MATE", Comment: "Use the Sawfish window manager inside of the MATE desktop environment",
		DesktopNames: []string{"MATE"}, // mate-session
		Exec:         "sawfish-mate-session",
		OwnAutostart: true,
	},
	"sawfish-xfce.desktop": {
		Name: "Sawfish/XFCE", Comment: "Use the Sawfish window manager inside of the XFCE desktop environment",
		DesktopNames: []string{"XFCE"}, // startxfce4
		Exec:         "sawfish-xfce-session",
		OwnAutostart: true,
	},
	"xmonad-mate.desktop": {
		Name: "xmonad-mate", Comment: "Tiling window manager",
		DesktopNames: []string{"MATE"}, // mate-session
		Exec:         "xmonad-start mate-session",
		OwnAutostart: true,
	},

	// Window managers.
	"awesome.desktop": {
		Name: "awesome", Comment: "Highly configurable framework window manager",
		DesktopNames: []string{"awesome"}, // none
		Exec:         "awesome",
	},
	"blackbox.desktop": {
		Name: "blackbox", Comment: "This session logs you into Blackbox",
		DesktopNames: []string{"blackbox"}, // none
		Exec:         "blackbox",
	},
	"bspwm.desktop": {
		Name: "bspwm", Comment: "Binary space partitioning window manager",
		DesktopNames: []string{"bspwm"}, // Arch, Debian
		Exec:         "bspwm",
	},
	"cwm.desktop": {
		Name: "cwm", Comment: "Lightweight window manager for X11",
		DesktopNames: []string{"cwm"}, // Fedora
		Exec:         "cwm",
	},
	"dwm.desktop": {
		Name: "dwm", Comment: "dynamic window manager",
		DesktopNames: []string{"dwm"}, // Debian
		Exec:         "dwm",
	},
	"fluxbox.desktop": {
		Name: "fluxbox", Comment: "Highly configurable and low resource X11 Window manager",
		DesktopNames: []string{"fluxbox"}, // none
		Exec:         "startfluxbox",
	},
	"fvwm3.desktop": {
		Name: "FVWM3", Comment: "F? Virtual Window Manager",
		DesktopNames: []string{"FVWM3", "FVWM"}, // Arch, Debian
		Exec:         "fvwm3",
	},
	"herbstluftwm.desktop": {
		Name: "herbstluftwm", Comment: "Manual tiling window manager",
		DesktopNames: []string{"herbstluftwm"}, // none
		Exec:         "herbstluftwm",
	},
	"i3.desktop": {
		Name: "i3", Comment: "improved dynamic tiling window manager",
		DesktopNames: []string{"i3"}, // all
		Exec:         "i3",
	},
	"icewm.desktop": {
		Name: "IceWM", Comment: "Simple and fast window manager",
		DesktopNames: []string{"ICEWM"}, // all
		Exec:         "icewm",
	},
	// icewm-session starts IceWM's components—the window manager, background,
	// and tray—and does not touch XDG autostart; this was tested on Arch (4.1.0)
	// and Ubuntu (3.4.5). User content in ~/.icewm/startup is analogous to bspwm's
	// bspwmrc and unrelated to these entries.
	"icewm-session.desktop": {
		Name: "IceWM Session", Comment: "This session logs you into IceWM",
		DesktopNames: []string{"ICEWM"}, // all
		Exec:         "icewm-session",
	},
	"jwm.desktop": {
		Name: "JWM", Comment: "Minimalistic pure X11 window manager with menu/tray support",
		DesktopNames: []string{"jwm"}, // none
		Exec:         "jwm",
	},
	"openbox.desktop": {
		Name: "Openbox", Comment: "Log in using the Openbox window manager (without a session manager)",
		DesktopNames: []string{"openbox"}, // none
		Exec:         "openbox-session",
	},
	"pekwm.desktop": {
		Name: "PekWM", Comment: "Tabbed X11 window manager",
		DesktopNames: []string{"pekwm"}, // none
		Exec:         "pekwm",
	},
	"qtile.desktop": {
		Name: "Qtile", Comment: "Qtile Session",
		DesktopNames: []string{"qtile"}, // Arch
		Exec:         "qtile start",
	},
	"spectrwm.desktop": {
		Name: "spectrwm", Comment: "The spectrwm window manager",
		DesktopNames: []string{"spectrwm"}, // Debian
		Exec:         "spectrwm",
	},
	"stumpwm.desktop": {
		Name: "Stumpwm", Comment: "Tiling, keyboard driven Common Lisp window manager",
		DesktopNames: []string{"stumpwm"}, // none
		Exec:         "stumpwm",
	},
	"wmaker.desktop": {
		Name: "Window Maker", Comment: "This session logs you into Window Maker",
		DesktopNames: []string{"WindowMaker"}, // all
		Exec:         "wmaker",
	},
	"xmonad.desktop": {
		Name: "Xmonad", Comment: "Lightweight X11 tiled window manager written in Haskell",
		DesktopNames: []string{"xmonad"}, // none
		Exec:         "xmonad",
	},
}
